# Generated by Django 3.2.4 on 2021-06-25 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_phone_nomber_profile_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='biographt',
            new_name='biography',
        ),
    ]
